"""
Atlas Constants - Colors. FRS-v1.0 locked. STATUS: FROZEN
"""
COLOR_NORMAL   = "#3B72D9"
COLOR_WEIGHT   = "#1A8C42"
COLOR_TENSION  = "#DC2626"
COLOR_FRICTION = "#D4560B"
COLOR_APPLIED  = "#7C3AED"
COLOR_NAVY     = "#1A2744"
COLOR_SLATE    = "#64748B"
COLOR_BG       = "#FFFFFF"
COLOR_BLOCK    = "#EFF6FF"
COLOR_GROUND   = "#D1D5DB"
COLOR_HATCH    = "#6B7280"
COLOR_BLACK    = "#000000"
COLOR_ROPE_OUTER = "#3D1F0A"
COLOR_ROPE_MID   = "#C87941"
COLOR_ROPE_HI    = "#E8A84A"
COLOR_CORRECT  = "#DCFCE7"
COLOR_WRONG    = "#FEE2E2"
COLOR_SELECTED = "#FEF3C7"

VALID_FORCE_COLORS = {
    "N": COLOR_NORMAL, "mg": COLOR_WEIGHT, "T": COLOR_TENSION,
    "f": COLOR_FRICTION, "F": COLOR_APPLIED,
}

def get_force_color(name):
    if name not in VALID_FORCE_COLORS:
        raise ValueError(f"Unknown force '{name}'. Valid: {list(VALID_FORCE_COLORS)}")
    return VALID_FORCE_COLORS[name]
